### ISSUE TITLE
PersistentChalk crashes on startup

### ISSUE THREAD

**Issue by ShadowJonathan** [DrMeepso/CovePlugins#4]
```
[Persistent Chalk] Chalk data file found. Loading chalk data...
Unhandled exception. System.InvalidOperationException: Each parameter in the deserialization constructor on type 'Cove.Server.Chalk.ChalkCanvas' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at PersistentChalk.PersistentChalk.loadChalk(Byte[] chalkData)
   at PersistentChalk.PersistentChalk.onInit()
   at Cove.Server.CoveServer.loadAllPlugins() in /home/runner/work/WebFishingCove/WebFishingCove/Cove/Server/Plugins/Server.Plugins.cs:line 69
   at Cove.Server.CoveServer.Init() in /home/runner/work/WebFishingCove/WebFishingCove/Cove/Server/Server.cs:line 190
   at Program.<Main>$(String[] args) in /home/runner/work/WebFishingCove/WebFishingCove/Cove/Program.cs:line 22
```

**Comment by ShadowJonathan** [comment]
Fixed by 3051f4e1f59601f76407d00bb6cb59c046224cf0
