### ISSUE TITLE
PersistentChalk needs some changes on WebFishingCove to properly save chalk data

### ISSUE THREAD

**Issue by ShadowJonathan** [DrMeepso/CovePlugins#5]
First, there's this little patch where the `chalkImage` needs to be made `public` before it can be serialised/unserialised:

`Cove/Server/Chalk/ChalkCanvas.cs`:
```diff
     {
 
         public long canvasID;
-        Dictionary<Vector2, int> chalkImage = new Dictionary<Vector2, int>();
+        public Dictionary<Vector2, int> chalkImage = new Dictionary<Vector2, int>();
 
         public ChalkCanvas(long canvasID)
         {
```

However, trying to save chalk data then results in this error:

<details>
<summary>Long exception (click to open)</summary>

```
Unhandled exception. System.NotSupportedException: The type 'Cove.GodotFormat.Vector2' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[Cove.GodotFormat.Vector2,System.Single,System.Single,System.Object,System.Object]'. Custom converters can add support for dictionary key serialization by overriding the 'ReadAsPropertyName' and 'WriteAsPropertyName' methods. The unsupported member type is located on type 'System.Int32'. Path: $.chalkImage.
 ---> System.NotSupportedException: The type 'Cove.GodotFormat.Vector2' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[Cove.GodotFormat.Vector2,System.Single,System.Single,System.Object,System.Object]'. Custom converters can add support for dictionary key serialization by overriding the 'ReadAsPropertyName' and 'WriteAsPropertyName' methods.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyNameCore(Utf8JsonWriter writer, T value, JsonSerializerOptions options, Boolean isWritingExtensionDataProperty)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, Exception innerException)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at PersistentChalk.PersistentChalk.saveChalk()
   at Cove.Server.HostedServices.ActorUpdateService.DoWork(Object state) in /Users/j0j0/dev/WebFishingCove/Cove/Server/HostedServices/ActorUpdate.cs:line 63
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

</details>

Fundamentally, this is saying that `Vector2` cannot be a JSON dictionary key, a string.

I can recommend reading [this SO answer](https://stackoverflow.com/a/31412665) on how to implement it, but basically; You'd implement a type converter for `Vector2`, and then add the annotation/attribute `[TypeConverter(typeof(MyClassConverter))]` to `Vector2` (and others)

**Comment by ShadowJonathan** [comment]
These fixes were essentially implemented with https://github.com/DrMeepso/CovePlugins/commit/3051f4e1f59601f76407d00bb6cb59c046224cf0 and https://github.com/DrMeepso/WebFishingCove/commit/fee4fb9103f84770253872d1986ea774d78c39c6
